// Round-6 runner. Sits at NgWorkspace/iptv-astro/round6-patch.mjs.
// __dirname here = that exact path. path.resolve(__dirname, '..', 'cihgames-pronostics')
// correctly resolves to NgWorkspace/cihgames-pronostics (the REAL target).
//
// Also applies 2 polish items from reviewer:
// - probeLoggedIn uses PREDICTIONS_URLS fallback list (so it doesn't fail on /my_predictions alone)
// - login submit click timeout bumped to 8s for slow bank WAFs.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(__dirname, '..', 'cihgames-pronostics');

function w(rel, content) {
  const p = path.join(OUT, rel);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content);
  console.log('wrote ' + rel + ' (' + content.length + ' bytes)');
}

// ============================================================
// src/actions/login.js
// ============================================================
const login = [
  "import fs from 'node:fs';",
  "import path from 'node:path';",
  "import { logger } from '../logger.js';",
  "import { onLoginPath } from '../browser.js';",
  "",
  "const BASE = 'https://cihgames.ma';",
  "const DEBUG_DIR = path.resolve('./debug');",
  "if (!fs.existsSync(DEBUG_DIR)) fs.mkdirSync(DEBUG_DIR, { recursive: true });",
  "",
  "// Try multiple URLs in order. Real dest after login is /pronostics.php per",
  "// captured HTML's hidden `next` field. /my_predictions is the historic guess.",
  "export const PREDICTIONS_URLS = [BASE + '/pronostics.php', BASE + '/my_predictions'];",
  "",
  "// Match common placeholder text shipped in .env.example so a forgetful user",
  "// gets a clear error instead of 'Login failed: '.",
  "const PLACEHOLDER = /your\\.email@example\\.com|your[-_ ]?password|changeme|example\\.com/i;",
  "",
  "// Real cihgames.ma button (from captured HTML) is <button class=\"btn\">Connexion</button>.",
  "// It has NO type=\"submit\", NO id, NO btn-primary class.",
  "const EMAIL_SELECTORS = [",
  "  '#login-email',",
  "  '#email',",
  "  'input[name=\"email\"]',",
  "  'input[type=\"email\"]'",
  "];",
  "const PASSWORD_SELECTORS = [",
  "  '#login-password',",
  "  '#password',",
  "  'input[name=\"password\"]',",
  "  'input[type=\"password\"]'",
  "];",
  "const SUBMIT_SELECTORS = [",
  "  // Real cihgames.ma button (Bootstrap-style).",
  "  'form.login-form button.btn',",
  "  'form button.btn',",
  "  // Standard HTML submission types.",
  "  'form button[type=\"submit\"]',",
  "  'form input[type=\"submit\"]',",
  "  'button[type=\"submit\"]',",
  "  'input[type=\"submit\"]',",
  "  // Default-type button inside a form is implicitly submit.",
  "  'form button:not([type])',",
  "  'form.login-form > button',",
  "  // Catch-all by visible text.",
  "  'button:has-text(\"Connexion\")',",
  "  'button:has-text(\"Se connecter\")',",
  "  'button:has-text(\"Log in\")',",
  "  'button:has-text(\"Connex\")',",
  "  // Other fallbacks.",
  "  '#submit',",
  "  '#login-submit',",
  "  'button.btn-primary',",
  "  '.login-btn'",
  "];",
  "",
  "async function firstAvailable(page, selectors) {",
  "  for (const sel of selectors) {",
  "    try {",
  "      const c = await page.locator(sel).count();",
  "      if (c > 0) return sel;",
  "    } catch (e) { /* fall through */ }",
  "  }",
  "  return null;",
  "}",
  "",
  "async function snapshot(page, name) {",
  "  try {",
  "    const stamp = new Date().toISOString().replace(/[:.]/g, '-');",
  "    const htmlName = 'login-' + name + '-' + stamp + '.html';",
  "    const pngName  = 'login-' + name + '-' + stamp + '.png';",
  "    fs.writeFileSync(path.join(DEBUG_DIR, htmlName), await page.content());",
  "    await page.screenshot({ path: path.join(DEBUG_DIR, pngName), fullPage: true }).catch(function () {});",
  "    logger.info({ step: name, html: htmlName, png: pngName }, 'login snapshot');",
  "    return { htmlName: htmlName, pngName: pngName };",
  "  } catch (e) {",
  "    logger.warn({ err: e.message, step: name }, 'snapshot failed');",
  "    return null;",
  "  }",
  "}",
  "",
  "async function submitLoginForm(page) {",
  "  logger.info({ url: BASE + '/login' }, 'Navigating to login page');",
  "  await page.goto(BASE + '/login', { waitUntil: 'domcontentloaded', timeout: 30_000 });",
  "  await snapshot(page, '01-loaded');",
  "",
  "  const emailSel = await firstAvailable(page, EMAIL_SELECTORS);",
  "  if (!emailSel) {",
  "    await snapshot(page, 'err-no-email-field');",
  "    throw new Error('Could not find the email field on /login — see debug/login-err-no-email-field-*.\\nCandidates tried: ' + EMAIL_SELECTORS.join(', '));",
  "  }",
  "",
  "  const passwordSel = await firstAvailable(page, PASSWORD_SELECTORS);",
  "  if (!passwordSel) {",
  "    await snapshot(page, 'err-no-password-field');",
  "    throw new Error('Could not find the password field on /login — see debug/login-err-no-password-field-*.\\nCandidates tried: ' + PASSWORD_SELECTORS.join(', '));",
  "  }",
  "",
  "  await page.fill(emailSel, process.env.CIH_EMAIL || '');",
  "  await page.fill(passwordSel, process.env.CIH_PASSWORD || '');",
  "  await snapshot(page, '02-filled');",
  "",
  "  const submitSel = await firstAvailable(page, SUBMIT_SELECTORS);",
  "  if (!submitSel) {",
  "    await snapshot(page, 'err-no-submit');",
  "    throw new Error('Could not find the submit button on /login — see debug/login-err-no-submit-*.\\nCandidates tried: ' + SUBMIT_SELECTORS.join(', ') + '.\\nIf cihgames.ma changed its button structure, append the new selector here. Open debug/login-01-loaded-* and search for <button.');",
  "  }",
  "  logger.info({ emailSel: emailSel, passwordSel: passwordSel, submitSel: submitSel }, 'Filling login form');",
  "",
  "  // Race the form submit against page navigation.",
  "  const navP = page.waitForNavigation({ waitUntil: 'domcontentloaded', timeout: 10_000 }).catch(function () { return null; });",
  "  let submitErr = null;",
  "  try {",
  "    // 8 s click timeout per reviewer: safer for slow bank WAFs.",
  "    await page.click(submitSel, { timeout: 8_000 });",
  "  } catch (err) {",
  "    submitErr = err;",
  "  }",
  "  await navP;",
  "  await snapshot(page, '03-after-submit');",
  "  if (submitErr) {",
  "    const snap = await snapshot(page, 'err-click-failed');",
  "    throw new Error('Submit button click failed (' + submitErr.message.split('\\n')[0] + '). The button exists but Playwright could not click it. Open debug/' + (snap ? snap.htmlName : '<latest>') + ' to see what cihgames.ma actually shows.');",
  "  }",
  "}",
  "",
  "// probeLoggedIn now uses PREDICTIONS_URLS fallback list (reviewer polish #4)",
  "// so it doesn't return false just because /my_predictions 404s while /pronostics.php works.",
  "async function probeLoggedIn(page) {",
  "  for (const url of PREDICTIONS_URLS) {",
  "    try {",
  "      await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 30_000 });",
  "      if (!onLoginPath(page.url())) return true;",
  "    } catch (err) {",
  "      logger.warn({ err: err.message, url: url }, 'probeLoggedIn URL failed');",
  "    }",
  "  }",
  "  return false;",
  "}",
  "",
  "async function confirmSessionEstablished(page) {",
  "  for (let i = 0; i < 6; i++) {",
  "    if (await probeLoggedIn(page)) return true;",
  "    await new Promise(function (r) { setTimeout(r, 500); });",
  "  }",
  "  return false;",
  "}",
  "",
  "async function sniffLoginError(page) {",
  "  if (!onLoginPath(page.url())) return null;",
  "  try {",
  "    return await page",
  "      .locator('.alert-danger, .error, [role=\"alert\"], .text-danger, .invalid-feedback, .form-error, .login-error, .flash-error, .message-error')",
  "      .first()",
  "      .textContent();",
  "  } catch (e) { return null; }",
  "}",
  "",
  "export async function login(page, opts) {",
  "  const retries = (opts && opts.retries) || 1;",
  "  const email = process.env.CIH_EMAIL;",
  "  const password = process.env.CIH_PASSWORD;",
  "  if (!email || !password || PLACEHOLDER.test(email) || PLACEHOLDER.test(password)) {",
  "    const err = new Error('CIH_EMAIL and CIH_PASSWORD are missing or still set to placeholder values. Copy .env.example to .env (.env is gitignored) and put your real cihgames.ma credentials in.');",
  "    err.code = 'NO_CREDENTIALS';",
  "    throw err;",
  "  }",
  "",
  "  let lastErr;",
  "  for (let attempt = 1; attempt <= retries + 1; attempt++) {",
  "    try {",
  "      logger.info({ attempt: attempt }, 'Login attempt');",
  "      await submitLoginForm(page);",
  "      if (await confirmSessionEstablished(page)) {",
  "        logger.info({ url: page.url() }, 'Login successful');",
  "        return;",
  "      }",
  "      const errMsg = await sniffLoginError(page);",
  "      throw new Error('Login failed: ' + (errMsg ? errMsg.trim() : 'session not established after submit. See debug/login-03-after-submit-* for what the page looks like.'));",
  "    } catch (err) {",
  "      lastErr = err;",
  "      logger.warn({ attempt: attempt, err: err.message }, 'Login attempt failed');",
  "    }",
  "  }",
  "  throw lastErr;",
  "}",
  "",
  "export async function ensureLoggedIn(page) {",
  "  if (await probeLoggedIn(page)) {",
  "    logger.info('Session already valid');",
  "    return;",
  "  }",
  "  logger.info('Session invalid, logging in');",
  "  await login(page);",
  "}",
  ""
].join('\n');
w('src/actions/login.js', login);

// ============================================================
// src/actions/updatePrediction.js
// ============================================================
const update = [
  "import fs from 'node:fs';",
  "import path from 'node:path';",
  "import { logger } from '../logger.js';",
  "import { onLoginPath } from '../browser.js';",
  "",
  "const BASE = 'https://cihgames.ma';",
  "const DEBUG_DIR = path.resolve('./debug');",
  "if (!fs.existsSync(DEBUG_DIR)) fs.mkdirSync(DEBUG_DIR, { recursive: true });",
  "const VALID_CHOICES = new Set(['1', 'X', '2']);",
  "",
  "async function findRow(page, id) {",
  "  const safeId = String(id).split('\"').join('\\\\\"');",
  "  const candidates = [",
  "    '[data-prono-id=\"' + safeId + '\"]',",
  "    '[data-prediction-id=\"' + safeId + '\"]',",
  "    '[data-match-id=\"' + safeId + '\"]',",
  "    '[data-fixture-id=\"' + safeId + '\"]',",
  "    '[data-id=\"' + safeId + '\"]',",
  "    '#prono-' + safeId,",
  "    '#prediction-' + safeId,",
  "    '#match-' + safeId",
  "  ];",
  "  for (const sel of candidates) {",
  "    const c = await page.locator(sel).count();",
  "    if (c > 0) return page.locator(sel).first();",
  "  }",
  "  return null;",
  "}",
  "",
  "function isRowLocked(locator) {",
  "  return locator.evaluate(function (el) {",
  "    if (el.matches('[data-locked=\"true\"], [data-disabled=\"true\"]')) return true;",
  "    if (el.querySelector('input[disabled], select[disabled], button[disabled], [aria-disabled=\"true\"]')) return true;",
  "    if (el.classList.contains('locked') || el.classList.contains('disabled') || el.classList.contains('verrouille')) return true;",
  "    return false;",
  "  }).catch(function () { return false; });",
  "}",
  "",
  "async function snapshotState(page, name, locator) {",
  "  try {",
  "    const stamp = new Date().toISOString().replace(/[:.]/g, '-');",
  "    const htmlName = 'update-' + name + '-' + stamp + '.html';",
  "    const pngName  = 'update-' + name + '-' + stamp + '.png';",
  "    fs.writeFileSync(path.join(DEBUG_DIR, htmlName), await page.content());",
  "    await page.screenshot({ path: path.join(DEBUG_DIR, pngName), fullPage: true }).catch(function () {});",
  "    if (locator) {",
  "      const outer = await locator.evaluate(function (el) { return el.outerHTML; }).catch(function () { return ''; });",
  "      if (outer) fs.writeFileSync(path.join(DEBUG_DIR, 'update-' + name + '-' + stamp + '-row.html'), outer);",
  "    }",
  "    logger.info({ step: name, html: htmlName, png: pngName }, 'update snapshot');",
  "    return { htmlName: htmlName, pngName: pngName };",
  "  } catch (e) {",
  "    logger.warn({ err: e.message, step: name }, 'update snapshot failed');",
  "    return null;",
  "  }",
  "}",
  "",
  "async function safeClick(locator, label) {",
  "  try {",
  "    await locator.click({ timeout: 5_000 });",
  "    return null;",
  "  } catch (err) {",
  "    return new Error('Click failed on ' + label + ' (' + err.message.split('\\n')[0] + '). The element exists but is not interactable — usually hidden, under a modal/CAPTCHA, or the row structure differs from what the script expects.');",
  "  }",
  "}",
  "",
  "async function applyChoice(page, locator, choice) {",
  "  const submit = locator.locator('form button[type=\"submit\"], form input[type=\"submit\"], form button:not([type]), form button.btn').first();",
  "  const form = locator.locator('form').first();",
  "",
  "  const selectEl = locator.locator('select[name=\"prono\"], select[name=\"prediction\"], select[name=\"choice\"]').first();",
  "  if (await selectEl.count()) {",
  "    await selectEl.selectOption(choice);",
  "    return await submitForm(page, submit, form, 'select');",
  "  }",
  "",
  "  const radio = locator.locator('input[type=\"radio\"][value=\"' + choice + '\"]').first();",
  "  if (await radio.count()) {",
  "    await radio.check();",
  "    return await submitForm(page, submit, form, 'radio');",
  "  }",
  "",
  " const chipSel = [",
  "    '[data-value=\"' + choice + '\"]',",
  "    'button[data-choice=\"' + choice + '\"]',",
  "    '.choice[data-value=\"' + choice + '\"]'",
  "  ];",
  "  for (const sel of chipSel) {",
  "    const c = locator.locator(sel).first();",
  "    if (await c.count()) {",
  "      const err = await safeClick(c, 'chip(' + sel + ')');",
  "      if (err) {",
  "        await snapshotState(page, 'err-chip-click-' + choice.replace(/[^a-z0-9]/gi, '_'), locator);",
  "        throw err;",
  "      }",
  "      return await submitForm(page, submit, form, 'chip');",
  "    }",
  "  }",
  "  return null;",
  "}",
  "",
  "async function submitForm(page, submit, form, method) {",
  "  const predict = /prediction|prono|match|forecast/i;",
  "  const responsePromise = page",
  "    .waitForResponse(function (r) { return predict.test(r.url()) && r.request().method() === 'POST'; }, { timeout: 10_000 })",
  "    .catch(function () { return null; });",
  "",
  "  if (await submit.count()) {",
  "    const err = await safeClick(submit, 'submit(' + method + ')');",
  "    if (err) {",
  "      await snapshotState(page, 'err-submit-click-' + method, null);",
  "      throw err;",
  "    }",
  "  } else if (await form.count()) {",
  "    await form.evaluate(function (f) { f.submit(); });",
  "  } else {",
  "    throw new Error('Found an input mechanism but no <form> or submit button to send it');",
  "  }",
  "",
  "  const resp = await responsePromise;",
  "  if (resp) {",
  "    const status = resp.status();",
  "    if (status >= 400) {",
  "      throw new Error('Form submission rejected (HTTP ' + status + ' on ' + resp.url() + '). The site did not accept the update — inspect debug/update-* for the page state.');",
  "    }",
  "    logger.info({ method: method, status: status, url: resp.url() }, 'Prediction submitted and confirmed');",
  "    return { ok: true, method: method, status: status, url: resp.url() };",
  "  }",
  "",
  "  logger.warn({ method: method }, 'No matching POST response observed after submit.');",
  "  return { ok: true, method: method, status: null, unverified: true };",
  "}",
  "",
  "async function dumpRowDebug(page, locator, id) {",
  "  const outerHtml = await locator.evaluate(function (el) { return el.outerHTML; }).catch(function () { return ''; });",
  "  if (outerHtml) fs.writeFileSync(path.join(DEBUG_DIR, 'element-update-' + id + '.html'), outerHtml);",
  "  await page.screenshot({ path: path.join(DEBUG_DIR, 'element-update-' + id + '.png'), fullPage: false }).catch(function () {});",
  "}",
  "",
  "export async function updatePrediction(page, id, choice) {",
  "  if (!id) throw new Error('Prediction id required');",
  "  if (!VALID_CHOICES.has(choice)) throw new Error('Invalid choice \"' + choice + '\" — must be 1, X, or 2');",
  "",
  "  if (String(id).includes('|')) {",
  "    throw new Error('This prediction has no stable id from cihgames.ma. Open debug/predictions-*.html and extend CANDIDATE_SELECTORS in src/actions/getPredictions.js with the real attribute the site uses (e.g. data-fixture-id). Reload after fixing.');",
  "  }",
  "",
  "  await page.goto(BASE + '/my_predictions', { waitUntil: 'domcontentloaded', timeout: 30000 });",
  "  if (onLoginPath(page.url())) throw new Error('Not authenticated');",
  "  await page.waitForLoadState('networkidle', { timeout: 15000 }).catch(function () {});",
  "",
  "  const row = await findRow(page, id);",
  "  if (!row) {",
  "    await snapshotState(page, 'err-not-found-' + id.replace(/[^a-z0-9]/gi, '_'), null);",
  "    throw new Error('Prediction ' + id + ' not found on /my_predictions.');",
  "  }",
  "",
  "  if (await isRowLocked(row)) throw new Error('Prediction ' + id + ' is locked — cannot update');",
  "",
  "  const result = await applyChoice(page, row, choice);",
  "  if (!result) {",
  "    await dumpRowDebug(page, row, id);",
  "    await snapshotState(page, 'err-no-input-mechanism-' + id.replace(/[^a-z0-9]/gi, '_'), row);",
  "    throw new Error(\"Don't know how to update prediction \" + id + ' — no select/radio/chip input matched. See debug/update-err-no-input-mechanism-* . Adjust src/actions/updatePrediction.js to match the actual DOM.');",
  "  }",
  "  return Object.assign({}, result, { id: id, choice: choice });",
  "}",
  ""
].join('\n');
w('src/actions/updatePrediction.js', update);

// ============================================================
// src/actions/getPredictions.js
// ============================================================
const get = [
  "import fs from 'node:fs';",
  "import path from 'node:path';",
  "import { logger } from '../logger.js';",
  "import { onLoginPath } from '../browser.js';",
  "",
  "const BASE = 'https://cihgames.ma';",
  "const DEBUG_DIR = path.resolve('./debug');",
  "if (!fs.existsSync(DEBUG_DIR)) fs.mkdirSync(DEBUG_DIR, { recursive: true });",
  "",
  "// Try /pronostics.php FIRST (it's the `next` field in the login form),",
  "// fall back to /my_predictions.",
  "const PREDICTIONS_URLS = [BASE + '/pronostics.php', BASE + '/my_predictions'];",
  "",
  "const CANDIDATE_SELECTORS = [",
  "  '[data-prono-id]',",
  "  '[data-prediction-id]',",
  "  '[data-match-id]',",
  "  '[data-fixture-id]',",
  "  '[data-id*=\"prono\" i]',",
  "  '[data-id*=\"match\" i]',",
  "  '.prediction-item',",
  "  '.prono-item',",
  "  '.match-prediction',",
  "  '.match-card',",
  "  '.match-prono',",
  "  'tr.prono',",
  "  'tr.match',",
  "  'table tbody tr.match',",
  "  'table tbody tr[class*=\"prono\" i]',",
  "  'table tbody tr[class*=\"match\" i]',",
  "  'table tbody tr'",
  "];",
  "",
  "const FIELD_SELECTORS = {",
  "  homeTeam: '[data-home], .team-home, .home-team, [data-team-home], .home, .team-a, .team_a, .equipe-a, .equipe-domicile',",
  "  awayTeam: '[data-away], .team-away, .away-team, [data-team-away], .away, .team-b, .team_b, .equipe-b, .equipe-exterieur, .equipe-visiteur',",
  "  league:   '[data-league], .league, .competition, .championnat, .category, .competition-name',",
  "  date:     '[data-date], .date, .match-date, .datetime, .when, time, .match-time, .date-match',",
  "  current:  '[data-prono-value], [data-prediction-value], [data-current-prono], .prono-value, .current-prediction, .prediction-value, .value-current, [data-current], .value',",
  "  odds:     '[data-odds], .odds, .cote, .cotes',",
  "  status:   '[data-status], .status, .match-status, .state, .etat'",
  "};",
  "",
  "function synthId(p, idx) {",
  "  const key = [p.homeTeam, p.awayTeam, p.date, p.league].filter(Boolean).join('|').toLowerCase();",
  "  return key || ('row-' + idx);",
  "}",
  "",
  "function parseMatchDate(s) {",
  "  if (!s) return NaN;",
  "  const iso = Date.parse(s);",
  "  if (!Number.isNaN(iso)) return iso;",
  "  const m = String(s).match(/^(\\d{1,2})[\\/\\-\\.](\\d{1,2})[\\/\\-\\.](\\d{2,4})(?:[ T](\\d{1,2}):(\\d{2}))?$/);",
  "  if (m) {",
  "    let [, d, mo, y, h = '0', mi = '0'] = m;",
  "    if (y.length === 2) y = (Number(y) > 50 ? '19' : '20') + y;",
  "    return Date.UTC(Number(y), Number(mo) - 1, Number(d), Number(h), Number(mi));",
  "  }",
  "  return NaN;",
  "}",
  "",
  "function isLockedHeuristic(p) {",
  "  if (p.status) {",
  "    const s = p.status.toLowerCase();",
  "    if (/(termin|live|en cours|commenc|finished|played|closed|verrouill|verrouillé|locked)/.test(s)) return true;",
  "  }",
  "  const ts = parseMatchDate(p.date);",
  "  if (!Number.isNaN(ts) && ts < Date.now() - 30_000) return true;",
  "  return false;",
  "}",
  "",
  "export async function getPredictions(page) {",
  "  let lastErr;",
  "  for (const url of PREDICTIONS_URLS) {",
  "    try {",
  "      await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 30_000 });",
  "      if (!onLoginPath(page.url())) break;",
  "    } catch (err) {",
  "      lastErr = err;",
  "      logger.warn({ url: url, err: err.message }, 'predictions URL failed');",
  "    }",
  "  }",
  "  if (onLoginPath(page.url())) throw new Error('Still on /login after navigation — session invalid');",
  "  await page.waitForLoadState('networkidle', { timeout: 15_000 }).catch(function () {});",
  "",
  "  const stamp = new Date().toISOString().replace(/[:.]/g, '-');",
  "  const htmlName = 'predictions-' + stamp + '.html';",
  "  const pngName  = 'predictions-' + stamp + '.png';",
  "  fs.writeFileSync(path.join(DEBUG_DIR, htmlName), await page.content());",
  "  await page.screenshot({ path: path.join(DEBUG_DIR, pngName), fullPage: true }).catch(function () {});",
  "  logger.info({ htmlName: htmlName, pngName: pngName }, 'Saved predictions debug snapshot');",
  "",
  "  let selector = null;",
  "  for (const sel of CANDIDATE_SELECTORS) {",
  "    const n = await page.locator(sel).count();",
  "    if (n > 0) { selector = sel; break; }",
  "  }",
  "",
  "  let raw = [];",
  "  if (selector) {",
  "    raw = await page.$$eval(selector, function (els, FS) {",
  "      const txt = function (s) {",
  "        for (const x of s.split(',').map(function (v) { return v.trim(); })) {",
  "          const node = el.querySelector(x);",
  "          if (node) {",
  "            const t = node.textContent ? node.textContent.trim() : '';",
  "            if (t) return t;",
  "          }",
  "        }",
  "        return null;",
  "      };",
  "      return els.map(function (el, idx) {",
  "        return {",
  "          id: el.getAttribute('data-prono-id')",
  "            || el.getAttribute('data-prediction-id')",
  "            || el.getAttribute('data-match-id')",
  "            || el.getAttribute('data-fixture-id')",
  "            || el.getAttribute('data-id')",
  "            || (el.id ? el.id.replace(/^prono-?/, '').replace(/^prediction-?/, '').replace(/^match-?/, '') : null)",
  "            || null,",
  "          homeTeam: txt(FS.homeTeam),",
  "          awayTeam: txt(FS.awayTeam),",
  "          league:   txt(FS.league),",
  "          date:     txt(FS.date),",
  "          currentPrediction: txt(FS.current),",
  "          odds:     txt(FS.odds),",
  "          status:   txt(FS.status),",
  "          index: idx",
  "        };",
  "      });",
  "    }, FIELD_SELECTORS).catch(function (err) {",
  "      logger.warn({ err: err.message }, '$$eval failed');",
  "      return [];",
  "    });",
  "  }",
  "",
  "  if (!selector) {",
  "    logger.warn('No candidate selector matched. Inspect debug/' + htmlName + ' and extend CANDIDATE_SELECTORS in src/actions/getPredictions.js');",
  "    return { items: [], debug: { htmlPath: '/debug/' + htmlName, pngPath: '/debug/' + pngName, selector: null }, fetchedAt: new Date().toISOString() };",
  "  }",
  "",
  "  const items = raw.map(function (p, idx) {",
  "    const id = p.id || synthId(p, idx);",
  "    return { id: id, homeTeam: p.homeTeam, awayTeam: p.awayTeam, league: p.league, date: p.date, currentPrediction: p.currentPrediction, odds: p.odds, status: p.status, locked: isLockedHeuristic(p) };",
  "  });",
  "",
  "  items.sort(function (a, b) {",
  "    if (a.locked !== b.locked) return a.locked ? 1 : -1;",
  "    const da = Date.parse(a.date || '') || Infinity;",
  "    const db = Date.parse(b.date || '') || Infinity;",
  "    return da - db;",
  "  });",
  "",
  "  return { items: items, debug: { htmlPath: '/debug/' + htmlName, pngPath: '/debug/' + pngName, selector: selector }, fetchedAt: new Date().toISOString() };",
  "}",
  ""
].join('\n');
w('src/actions/getPredictions.js', get);

// ============================================================
// public/app.js
// ============================================================
const app = [
  "function $(sel, root) { return root ? root.querySelector(sel) : document.querySelector(sel); }",
  "",
  "function escapeHtml(s) {",
  "  return String(s == null ? '' : s).replace(/[&<>\"']/g, function (c) {",
  "    return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;', \"'\": '&#39;' }[c];",
  "  });",
  "}",
  "",
  "function formatError(err) {",
  "  const m = String(err && err.message ? err.message : err || '');",
  "  if (/locator\\.click.*(timeout|exceeded)|Click failed on|Could not find (the )?submit button|No such element|net::ERR/i.test(m)) {",
  "    return 'Page automation failed (' + m.split('\\n')[0] + '). ' +",
  "      'Open <a href=\"/api/debug/peek\" target=\"_blank\">/api/debug/peek</a> ' +",
  "      'to see the most recent captured page state. ' +",
  "      'Also visit <a href=\"/api/debug\" target=\"_blank\">/api/debug</a> for the full list of captures.';",
  "  }",
  "  return m;",
  "}",
  "",
  "const state = { items: [], debug: null, saving: null, busy: false };",
  "",
  "function setStatus(text, kind) {",
  "  const el = $('#status');",
  "  if (!el) return;",
  "  el.textContent = text;",
  "  el.className = 'status' + (kind ? ' ' + kind : '');",
  "}",
  "",
  "function bannerDebugLink() {",
  "  if (!state.debug || !state.debug.htmlPath) return '';",
  "  const href = state.debug.htmlPath.startsWith('/') ? state.debug.htmlPath : '/' + state.debug.htmlPath;",
  "  return '<p class=\"hint\"><a href=\"' + escapeHtml(href) + '\" target=\"_blank\">View captured page HTML</a> — ' +",
  "    'open it (right-click → view source) and search for \"data-prono\" or \"match\" to learn what selectors the site uses.</p>';",
  "}",
  "",
  "function render() {",
  "  const app = $('#app');",
  "  if (!state.items.length) {",
  "    app.innerHTML =",
  "      '<p class=\"empty\">No predictions loaded yet.</p>' +",
  "      '<p class=\"hint\">Click <b>Refresh predictions</b> above. If the table stays empty, the captured page HTML below will tell us what DOM selectors to add.</p>' +",
  "      bannerDebugLink();",
  "    return;",
  "  }",
  "  app.innerHTML = '<table class=\"grid\"><thead><tr>' +",
  "    '<th>Match</th><th>Compétition</th><th>Date</th><th>Cote</th><th>Mon pronostic</th><th></th>' +",
  "    '</tr></thead><tbody>' +",
  "    state.items.map(itemToRow).join('') +",
  "    '</tbody></table>';",
  "}",
  "",
  "function itemToRow(it) {",
  "  const family = (it.homeTeam && it.awayTeam)",
  "    ? escapeHtml(it.homeTeam) + ' vs ' + escapeHtml(it.awayTeam)",
  "    : '<span class=\"muted\">' + escapeHtml(it.id) + '</span>';",
  "  const dLock = it.locked ? ' <span class=\"locked\" title=\"verrouillé\">lock</span>' : '';",
  "  const dChoices = it.locked",
  "    ? '<span class=\"muted\">locked</span>'",
  "    : ['1', 'X', '2'].map(function (c) {",
  "        return '<button class=\"btn-choice\" data-id=\"' + escapeHtml(it.id) + '\" data-choice=\"' + c + '\"' +",
  "          (state.saving === it.id ? ' disabled' : '') + '>' + c + '</button>';",
  "      }).join('');",
  "  return '<tr' + (it.locked ? ' class=\"locked\"' : '') + '>' +",
  "    '<td><b>' + family + '</b>' + dLock + '</td>' +",
  "    '<td>' + escapeHtml(it.league || '') + '</td>' +",
  "    '<td>' + escapeHtml(it.date || '') + '</td>' +",
  "    '<td>' + escapeHtml(it.odds || '') + '</td>' +",
  "    '<td>' + escapeHtml(it.currentPrediction || '-') + '</td>' +",
  "    '<td>' + dChoices + '</td>' +",
  "    '</tr>';",
  "}",
  "",
  "async function refresh() {",
  "  if (state.busy) return;",
  "  state.busy = true;",
  "  setStatus('Loading…', 'busy');",
  "  try {",
  "    const res = await fetch('/api/predictions', { method: 'GET' });",
  "    const data = await res.json().catch(function () { return {}; });",
  "    if (!res.ok) throw new Error((data && data.error) || ('HTTP ' + res.status));",
  "    state.items = Array.isArray(data.items) ? data.items : [];",
  "    state.debug = data.debug || null;",
  "    setStatus(state.items.length + ' prediction(s)', state.items.length ? 'ok' : 'warn');",
  "    render();",
  "  } catch (err) {",
  "    setStatus('Error', 'err');",
  "    $('#app').innerHTML =",
  "      '<p class=\"error\">' + escapeHtml(formatError(err)) + '</p>' +",
  "      '<p class=\"hint\">Visit <a href=\"/api/debug\" target=\"_blank\">/api/debug</a> for the full list of captures, and <a href=\"/api/debug/peek\" target=\"_blank\">/api/debug/peek</a> for the latest captured HTML.</p>';",
  "  } finally {",
  "    state.busy = false;",
  "  }",
  "}",
  "",
  "async function save(id, choice) {",
  "  if (state.busy) return;",
  "  state.saving = id;",
  "  setStatus('Saving ' + choice + ' on ' + id + '…', 'busy');",
  "  render();",
  "  try {",
  "    const res = await fetch('/api/predictions/' + encodeURIComponent(id), {",
  "      method: 'POST',",
  "      headers: { 'content-type': 'application/json' },",
  "      body: JSON.stringify({ choice: choice })",
  "    });",
  "    const data = await res.json().catch(function () { return {}; });",
  "    if (!res.ok) throw new Error((data && data.error) || ('HTTP ' + res.status));",
  "    if (data.unverified) setStatus('Saved (unverified - verify on the site)', 'warn');",
  "    else if (data.status && data.status >= 400) setStatus('Server rejected update', 'err');",
  "    else setStatus('Saved', 'ok');",
  "    const it = state.items.find(function (x) { return x.id === id; });",
  "    if (it) it.currentPrediction = choice;",
  "    render();",
  "    return data;",
  "  } catch (err) {",
  "    setStatus('Save failed', 'err');",
  "    $('#app').innerHTML =",
  "      '<p class=\"error\">' + escapeHtml(formatError(err)) + '</p>' +",
  "      '<p class=\"hint\">Visit <a href=\"/api/debug\" target=\"_blank\">/api/debug</a> for the latest captures.</p>';",
  "  } finally {",
  "    state.saving = null;",
  "  }",
  "}",
  "",
  "document.addEventListener('DOMContentLoaded', function () {",
  "  const btn = document.getElementById('refresh-btn');",
  "  if (btn) btn.addEventListener('click', refresh);",
  "  const app = document.getElementById('app');",
  "  if (app) app.addEventListener('click', function (ev) {",
  "    const b = ev.target.closest ? ev.target.closest('.btn-choice') : null;",
  "    if (!b) return;",
  "    save(b.dataset.id, b.dataset.choice);",
  "  });",
  "  refresh();",
  "});",
  ""
].join('\n');
w('public/app.js', app);

// ============================================================
// src/routes/debug.js
// ============================================================
const debug = [
  "import fs from 'node:fs';",
  "import path from 'node:path';",
  "import { Router } from 'express';",
  "",
  "const DEBUG_DIR = path.resolve('./debug');",
  "if (!fs.existsSync(DEBUG_DIR)) fs.mkdirSync(DEBUG_DIR, { recursive: true });",
  "",
  "const router = Router();",
  "",
  "function listDebugFiles() {",
  "  return fs.readdirSync(DEBUG_DIR)",
  "    .filter(function (f) { return !f.startsWith('.'); })",
  "    .map(function (name) {",
  "      const full = path.join(DEBUG_DIR, name);",
  "      const st = fs.statSync(full);",
  "      return { name: name, size: st.size, mtime: st.mtime.toISOString() };",
  "    })",
  "    .sort(function (a, b) { return b.mtime.localeCompare(a.mtime); });",
  "}",
  "",
  "router.get('/', function (req, res) { res.json({ files: listDebugFiles() }); });",
  "",
  "// Peek at the most recent predictions HTML so the user can paste it into",
  "// chat without manually opening files. Capped at 60 KB.",
  "router.get('/peek', function (req, res) {",
  "  const files = listDebugFiles().filter(function (f) {",
  "    return f.name.startsWith('predictions-') && f.name.endsWith('.html');",
  "  });",
  "  if (!files.length) {",
  "    res.type('text/plain').send(",
  "      'No predictions debug files yet. Click \"Refresh predictions\" once and the app will save a snapshot. ' +",
  "      'If the snapshot is still missing, the request died before getPredictions.js could write it; check the server logs and visit /api/debug for the file list.'",
  "    );",
  "    return;",
  "  }",
  "  const latest = files[0];",
  "  const full = path.join(DEBUG_DIR, latest.name);",
  "  let body = fs.readFileSync(full, 'utf8');",
  "  if (body.length > 60_000) {",
  "    body = '<!-- TRUNCATED at 60 KB - open the raw file in debug/ for the rest --->\\n' + body.slice(0, 60_000);",
  "  }",
  "  res.type('text/plain').send(body);",
  "});",
  "",
  "// Serve any file from debug/ directly. Used by the UI empty-state link.",
  "router.get('/raw', function (req, res) {",
  "  const name = req.query.file ? String(req.query.file) : '';",
  "  const safe = path.basename(name);",
  "  if (!safe) { res.status(400).type('text/plain').send('Pass ?file=NAME'); return; }",
  "  const full = path.join(DEBUG_DIR, safe);",
  "  if (!full.startsWith(DEBUG_DIR) || !fs.existsSync(full)) {",
  "    res.status(404).type('text/plain').send('File not found in debug/: ' + safe);",
  "    return;",
  "  }",
  "  res.sendFile(full);",
  "});",
  "",
  "// Test arbitrary CSS selectors against the latest cached predictions HTML.",
  "router.get('/try', function (req, res) {",
  "  try {",
  "    const sel = req.query.sel ? String(req.query.sel) : '';",
  "    if (!sel) { res.status(400).json({ error: 'Pass ?sel=YOUR_CSS_SELECTOR' }); return; }",
  "    const real = listDebugFiles().filter(function (f) {",
  "      return f.name.startsWith('predictions-') && f.name.endsWith('.html');",
  "    });",
  "    if (!real.length) { res.status(404).json({ error: 'No cached predictions HTML yet - click Refresh first.' }); return; }",
  "    const html = fs.readFileSync(path.join(DEBUG_DIR, real[0].name), 'utf8');",
  "    const lower = sel.trim();",
  "    const esc = function (s) { return s.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&'); };",
  "    let regexStr = '<';",
  "    const tag = '[a-z][a-z0-9]*';",
  "    if (lower.startsWith('.') || lower.startsWith('#') || lower.startsWith('[')) {",
  "      if (lower.startsWith('.')) {",
  "        const cls = esc(lower.slice(1).split(/[\\s.[>+~:]/, 1)[0]);",
  "        regexStr += tag + '[^>]*class=\"[^\"]*\\\\b' + cls + '\\\\b';",
  "      } else if (lower.startsWith('#')) {",
  "        const id = esc(lower.slice(1).split(/[\\s.[>+~:]/, 1)[0]);",
  "        regexStr += tag + '[^>]*id=\"' + id + '\"';",
  "      } else if (lower.startsWith('[')) {",
  "        const close = lower.indexOf(']');",
  "        const attr = esc(lower.slice(1, close > 0 ? close : undefined));",
  "        regexStr += tag + '[^>]*' + attr;",
  "      }",
  "    } else {",
  " const tag2 = lower.split(/[\\s.[>+~:#]/, 1)[0];",
  "      regexStr += esc(tag2);",
  "    }",
  "    regexStr += '\\\\b';",
  "    const re = new RegExp(regexStr, 'gi');",
  "    const matches = html.match(re) || [];",
  "    res.json({ selector: sel, pattern: regexStr, matchCount: matches.length, sample: matches.slice(0, 3), cachedHtmlFile: real[0].name });",
  "  } catch (err) { res.status(500).json({ error: err.message }); }",
  "});",
  "",
  "export default router;",
  ""
].join('\n');
w('src/routes/debug.js', debug);

// Final verification ping so we know the path is correct.
console.log('OUT target: ' + OUT);
console.log('round6 patch complete');
