import fs from 'fs';
import path from 'path';

const dir = 'src/content/seoPages';
const files = fs.readdirSync(dir).filter(f => f.endsWith('.json'));

// Compact language dictionaries
const L = {
  fr: {
    'Best IPTV':'Meilleur IPTV','IPTV':'IPTV','for':'pour','in':'en','on':'sur',
    'Watch':'Regardez','Live':'en Direct','TV':'TV','Channels':'Chaînes',
    'Sports':'Sports','Guide':'Guide','Complete':'Complet','How to':'Comment',
    'Set Up':'Configurer','Install':'Installer','Why':'Pourquoi','Choose':'Choisir',
    'Available':'Disponible','with':'Avec','Service':'Service','Plan':'Abonnement',
    'Free Trial':'Essai Gratuit','Pricing':'Tarifs','Best':'Meilleur',
    'Get':'Obtenez','Learn':'Apprenez','Device':'Appareil','Devices':'Appareils',
    'Phone':'Téléphone','Phones':'Téléphones','Tablet':'Tablette','Tablets':'Tablettes',
    'Android':'Android','iPhone':'iPhone','iPad':'iPad','iOS':'iOS',
    'Smart TV':'Smart TV','Firestick':'Firestick','Fire TV Stick':'Fire TV Stick',
    'Samsung':'Samsung','LG':'LG','Sony':'Sony','Amazon':'Amazon',
    '4K':'4K','VOD':'VOD','Support 24/7':'Support 24/7',
    'Experience':'Expérience','Ultimate':'Ultime','Premium':'Premium',
    'Top':'Meilleur','Rated':'Noté','Features':'Fonctionnalités',
    'Start':'Commencer','Started':'Démarré','Step':'Étape',
    'Step-by-Step':'Pas à Pas','Setup':'Configuration',
    'What is':'Qu\'est-ce que','What Makes':'Ce Qui Fait',
    'Is':'Est','Legal':'Légal','Legality':'Légalité',
    'Technology':'Technologie','Works':'Fonctionne',
    'Streaming':'Streaming','Quality':'Qualité',
    'Content':'Contenu','Entertainment':'Divertissement',
    'Global':'Mondial','World':'Monde','Country':'Pays',
    'Abroad':'à l\'Étranger','International':'International',
    'Player':'Lecteur','App':'Application','Apps':'Applications',
    'Box':'Box','Compatibility':'Compatibilité',
    'All':'Tous','Any':'Tout','Every':'Chaque',
    'Favorite':'Préféré','Favorites':'Préférés',
    'News':'Actualités','Movies':'Films','Series':'Séries',
    'Match':'Match','Game':'Match','Games':'Matchs',
    'League':'Championnat','Premier League':'Premier League',
    'Football':'Football','Basketball':'Basketball',
    'Coverage':'Couverture','Included':'Inclus',
    'Watch from':'Regarder depuis',
    'and':'et','or':'ou','the':'le','a':'un',
    '–':'—','—':'—','-':'—',
  },
  es: {
    'Best IPTV':'Mejor IPTV','IPTV':'IPTV','for':'para','in':'en','on':'en',
    'Watch':'Mira','Live':'en Vivo','TV':'TV','Channels':'Canales',
    'Sports':'Deportes','Guide':'Guía','Complete':'Completa','How to':'Cómo',
    'Set Up':'Configurar','Install':'Instalar','Why':'Por Qué','Choose':'Elegir',
    'Available':'Disponible','with':'Con','Service':'Servicio','Plan':'Plan',
    'Free Trial':'Prueba Gratis','Pricing':'Precios','Best':'Mejor',
    'Get':'Obtén','Learn':'Aprende','Device':'Dispositivo','Devices':'Dispositivos',
    'Phone':'Teléfono','Phones':'Teléfonos','Tablet':'Tableta','Tablets':'Tabletas',
    'Android':'Android','iPhone':'iPhone','iPad':'iPad','iOS':'iOS',
    'Smart TV':'Smart TV','Firestick':'Firestick','Fire TV Stick':'Fire TV Stick',
    'Samsung':'Samsung','LG':'LG','Sony':'Sony','Amazon':'Amazon',
    '4K':'4K','VOD':'VOD','Support 24/7':'Soporte 24/7',
    'Experience':'Experiencia','Ultimate':'Definitiva','Premium':'Premium',
    'Top':'Mejor','Rated':'Valorado','Features':'Características',
    'Start':'Empezar','Started':'Comenzado','Step':'Paso',
    'Step-by-Step':'Paso a Paso','Setup':'Configuración',
    'What is':'Qué es','What Makes':'Qué Hace',
    'Is':'Es','Legal':'Legal','Legality':'Legalidad',
    'Technology':'Tecnología','Works':'Funciona',
    'Streaming':'Streaming','Quality':'Calidad',
    'Content':'Contenido','Entertainment':'Entretenimiento',
    'Global':'Mundial','World':'Mundo','Country':'País',
    'Abroad':'en el Extranjero','International':'Internacional',
    'Player':'Reproductor','App':'App','Apps':'Apps',
    'Box':'Box','Compatibility':'Compatibilidad',
    'All':'Todos','Any':'Cualquier','Every':'Cada',
    'Favorite':'Favorito','Favorites':'Favoritos',
    'News':'Noticias','Movies':'Películas','Series':'Series',
    'Match':'Partido','Game':'Partido','Games':'Partidos',
    'League':'Liga','Premier League':'Premier League',
    'Football':'Fútbol','Basketball':'Baloncesto',
    'Coverage':'Cobertura','Included':'Incluido',
    'Watch from':'Ver desde',
    'and':'y','or':'o','the':'el','a':'un',
    '–':'—','—':'—','-':'—',
  },
  de: {
    'Best IPTV':'Bestes IPTV','IPTV':'IPTV','for':'für','in':'in','on':'auf',
    'Watch':'Sehen Sie','Live':'Live','TV':'TV','Channels':'Sender',
    'Sports':'Sport','Guide':'Leitfaden','Complete':'Vollständig','How to':'So',
    'Set Up':'Einrichten','Install':'Installieren','Why':'Warum','Choose':'Wählen',
    'Available':'Verfügbar','with':'Mit','Service':'Dienst','Plan':'Abonnement',
    'Free Trial':'Kostenlose Testversion','Pricing':'Preise','Best':'Bestes',
    'Get':'Holen Sie','Learn':'Lernen Sie','Device':'Gerät','Devices':'Geräte',
    'Phone':'Handy','Phones':'Handys','Tablet':'Tablet','Tablets':'Tablets',
    'Android':'Android','iPhone':'iPhone','iPad':'iPad','iOS':'iOS',
    'Smart TV':'Smart TV','Firestick':'Firestick','Fire TV Stick':'Fire TV Stick',
    'Samsung':'Samsung','LG':'LG','Sony':'Sony','Amazon':'Amazon',
    '4K':'4K','VOD':'VOD','Support 24/7':'24/7-Support',
    'Experience':'Erlebnis','Ultimate':'Ultimativ','Premium':'Premium',
    'Top':'Beste','Rated':'Bewertet','Features':'Funktionen',
    'Start':'Starten','Started':'Gestartet','Step':'Schritt',
    'Step-by-Step':'Schritt-für-Schritt','Setup':'Einrichtung',
    'What is':'Was ist','What Makes':'Was macht',
    'Is':'Ist','Legal':'Legal','Legality':'Legalität',
    'Technology':'Technologie','Works':'Funktioniert',
    'Streaming':'Streaming','Quality':'Qualität',
    'Content':'Inhalt','Entertainment':'Unterhaltung',
    'Global':'Global','World':'Welt','Country':'Land',
    'Abroad':'im Ausland','International':'International',
    'Player':'Player','App':'App','Apps':'Apps',
    'Box':'Box','Compatibility':'Kompatibilität',
    'All':'Alle','Any':'Jedes','Every':'Jeden',
    'Favorite':'Lieblings','Favorites':'Lieblings',
    'News':'Nachrichten','Movies':'Filme','Series':'Serien',
    'Match':'Spiel','Game':'Spiel','Games':'Spiele',
    'League':'Liga','Premier League':'Premier League',
    'Football':'Fußball','Basketball':'Basketball',
    'Coverage':'Berichterstattung','Included':'Enthalten',
    'Watch from':'Ansehen von',
    'and':'und','or':'oder','the':'der','a':'ein',
    '–':'—','—':'—','-':'—',
  },
};

// Add it/pt translations (compact)
Object.assign(L, {
  it: {
    'Best IPTV':'Miglior IPTV','IPTV':'IPTV','for':'per','in':'in','on':'su',
    'Watch':'Guarda','Live':'Live','TV':'TV','Channels':'Canali',
    'Sports':'Sport','Guide':'Guida','Complete':'Completa','How to':'Come',
    'Set Up':'Configurare','Install':'Installa','Why':'Perché','Choose':'Scegliere',
    'Available':'Disponibile','with':'Con','Service':'Servizio','Plan':'Piano',
    'Free Trial':'Prova Gratuita','Pricing':'Prezzi','Best':'Miglior',
    'Get':'Ottieni','Learn':'Impara','Device':'Dispositivo','Devices':'Dispositivi',
    'Phone':'Telefono','Phones':'Telefoni','Tablet':'Tablet','Tablets':'Tablet',
    'Android':'Android','iPhone':'iPhone','iPad':'iPad','iOS':'iOS',
    'Smart TV':'Smart TV','Firestick':'Firestick','Fire TV Stick':'Fire TV Stick',
    'Samsung':'Samsung','LG':'LG','Sony':'Sony','Amazon':'Amazon',
    '4K':'4K','VOD':'VOD','Support 24/7':'Supporto 24/7',
    'Experience':'Esperienza','Ultimate':'Definitiva','Premium':'Premium',
    'Top':'Migliore','Rated':'Valutato','Features':'Funzionalità',
    'Start':'Iniziare','Started':'Iniziato','Step':'Passo',
    'Step-by-Step':'Passo-Passo','Setup':'Configurazione',
    'What is':'Cos\'è','What Makes':'Cosa Rende',
    'Is':'È','Legal':'Legale','Legality':'Legalità',
    'Technology':'Tecnologia','Works':'Funziona',
    'Streaming':
