import fs from 'fs';
import path from 'path';
const dir = 'src/content/seoPages';
const files = fs.readdirSync(dir).filter(f => f.endsWith('.json'));

const CN = {
fr:{france:'France',uk:'Royaume-Uni',usa:'États-Unis',germany:'Allemagne',greece:'Grèce',italy:'Italie',spain:'Espagne',portugal:'Portugal',canada:'Canada',australia:'Australie',brazil:'Brésil',mexico:'Mexique',argentina:'Argentine',chile:'Chili',colombia:'Colombie',peru:'Pérou',egypt:'Égypte',algeria:'Algérie',morocco:'Maroc',tunisia:'Tunisie',nigeria:'Nigeria','south-africa':'Afrique du Sud',kenya:'Kenya',ghana:'Ghana',india:'Inde',pakistan:'Pakistan',japan:'Japon',philippines:'Philippines',indonesia:'Indonésie',malaysia:'Malaisie',uae:'Émirats Arabes Unis','saudi-arabia':'Arabie Saoudite',qatar:'Qatar',kuwait:'Koweït',jordan:'Jordanie',lebanon:'Liban',iraq:'Irak',turkey:'Turquie',belgium:'Belgique',netherlands:'Pays-Bas',switzerland:'Suisse',sweden:'Suède',norway:'Norvège',poland:'Pologne',romania:'Roumanie',ireland:'Irlande',senegal:'Sénégal','cote-divoire':'Côte d\'Ivoire'},
es:{france:'Francia',uk:'Reino Unido',usa:'EE.UU.',germany:'Alemania',greece:'Grecia',italy:'Italia',spain:'España',portugal:'Portugal',canada:'Canadá',australia:'Australia',brazil:'Brasil',mexico:'México',argentina:'Argentina',chile:'Chile',colombia:'Colombia',peru:'Perú',egypt:'Egipto',algeria:'Argelia',morocco:'Marruecos',tunisia:'Túnez',nigeria:'Nigeria',kenya:'Kenia',ghana:'Ghana',india:'India',pakistan:'Pakistán',japan:'Japón',philippines:'Filipinas',indonesia:'Indonesia',malaysia:'Malasia',uae:'Emiratos Árabes','saudi-arabia':'Arabia Saudita',qatar:'Catar',kuwait:'Kuwait',jordan:'Jordania',lebanon:'Líbano',iraq:'Irak',turkey:'Turquía',belgium:'Bélgica',netherlands:'Países Bajos',switzerland:'Suiza',sweden:'Suecia',norway:'Noruega',poland:'Polonia',romania:'Rumanía',ireland:'Irlanda',senegal:'Senegal','cote-divoire':'Costa de Marfil'},
de:{france:'Frankreich',uk:'Großbritannien',usa:'USA',germany:'Deutschland',greece:'Griechenland',italy:'Italien',spain:'Spanien',portugal:'Portugal',canada:'Kanada',australia:'Australien',brazil:'Brasilien',mexico:'Mexiko',argentina:'Argentinien',chile:'Chile',colombia:'Kolumbien',peru:'Peru',egypt:'Ägypten',algeria:'Algerien',morocco:'Marokko',tunisia:'Tunesien',nigeria:'Nigeria',kenya:'Kenia',ghana:'Ghana',india:'Indien',pakistan:'Pakistan',japan:'Japan',philippines:'Philippinen',indonesia:'Indonesien',malaysia:'Malaysia',uae:'VAE','saudi-arabia':'Saudi-Arabien',qatar:'Katar',kuwait:'Kuwait',jordan:'Jordanien',lebanon:'Libanon',iraq:'Irak',turkey:'Türkei',belgium:'Belgien',netherlands:'Niederlande',switzerland:'Schweiz',sweden:'Schweden',norway:'Norwegen',poland:'Polen',romania:'Rumänien',ireland:'Irland',senegal:'Senegal','cote-divoire':'Elfenbeinküste'},
it:{france:'Francia',uk:'Regno Unito',usa:'USA',germany:'Germania',greece:'Grecia',italy:'Italia',spain:'Spagna',portugal:'Portogallo',canada:'Canada',australia:'Australia',brazil:'Brasile',mexico:'Messico',argentina:'Argentina',chile:'Cile',colombia:'Colombia',peru:'Perù',egypt:'Egitto',algeria:'Algeria',morocco:'Marocco',tunisia:'Tunisia',nigeria:'Nigeria',kenya:'Kenya',ghana:'Ghana',india:'India',pakistan:'Pakistan',japan:'Giappone',philippines:'Filippine',indonesia:'Indonesia',malaysia:'Malesia',uae:'EAU','saudi-arabia':'Arabia Saudita',qatar:'Qatar',kuwait:'Kuwait',jordan:'Giordania',lebanon:'Libano',iraq:'Iraq',turkey:'Turchia',belgium:'Belgio',netherlands:'Paesi Bassi',switzerland:'Svizzera',sweden:'Svezia',norway:'Norvegia',poland:'Polonia',romania:'Romania',ireland:'Irlanda',senegal:'Senegal','cote-divoire':'Costa d\'Avorio'},
pt:{france:'França',uk:'Reino Unido',usa:'EUA',germany:'Alemanha',greece:'Grécia',italy:'Itália',spain:'Espanha',portugal:'Portugal',canada:'Canadá',australia:'Austrália',brazil:'Brasil',mexico:'México',argentina:'Argentina',chile:'Chile',colombia:'Colômbia',peru:'Peru',egypt:'Egito',algeria:'Argélia',morocco:'Marrocos',tunisia:'Tunísia',nigeria:'Nigéria',kenya:'Quênia',ghana:'Gana',india:'Índia',pakistan:'Paquistão',japan:'Japão',philippines:'Filipinas',indonesia:'Indonésia',malaysia:'Malásia',uae:'EAU','saudi-arabia':'Arábia Saudita',qatar:'Catar',kuwait:'Kuwait',jordan:'Jordânia',lebanon:'Líbano',iraq:'Iraque',turkey:'Turquia',belgium:'Bélgica',netherlands:'Países Baixos',switzerland:'Suíça',sweden:'Suécia',norway:'Noruega',poland:'Polônia',romania:'Romênia',ireland:'Irlanda',senegal:'Senegal','cote-divoire':'Costa do Marfim'},
ar:{france:'فرنسا',uk:'المملكة المتحدة',usa:'الولايات المتحدة',germany:'ألمانيا',greece:'اليونان',italy:'إيطاليا',spain:'إسبانيا',portugal:'البرتغال',canada:'كندا',australia:'أستراليا',brazil:'البرازيل',mexico:'المكسيك',argentina:'الأرجنتين',chile:'تشيلي',colombia:'كولومبيا',peru:'بيرو',egypt:'مصر',algeria:'الجزائر',morocco:'المغرب',tunisia:'تونس',nigeria:'نيجيريا',kenya:'كينيا',ghana:'غانا',india:'الهند',pakistan:'باكستان',japan:'اليابان',philippines:'الفلبين',indonesia:'إندونيسيا',malaysia:'ماليزيا',uae:'الإمارات','saudi-arabia':'السعودية',qatar:'قطر',kuwait:'الكويت',jordan:'الأردن',lebanon:'لبنان',iraq:'العراق',turkey:'تركيا',belgium:'بلجيكا',netherlands:'هولندا',switzerland:'سويسرا',sweden:'السويد',norway:'النرويج',poland:'بولندا',romania:'رومانيا',ireland:'أيرلندا',senegal:'السنغال','cote-divoire':'ساحل العاج'}};

// Page-specific H1 templates per language and page type
const H1T = {
  country: {
    fr: (cn,enH1) => `Meilleur IPTV pour la ${cn} — TV ${cn==='France'?'Française':''} en Direct & Sports 4K`,
    es: (cn,enH1) => `Mejor IPTV para ${cn} — TV en Vivo y Deportes 4K`,
    de: (cn,enH1) => `Bestes IPTV für ${cn} — Live-TV & Sport in 4K`,
    it: (cn,enH1) => `Miglior IPTV per ${cn} — TV in Diretta e Sport 4K`,
    pt: (cn,enH1) => `Melhor IPTV para ${cn} — TV ao Vivo e Esportes 4K`,
    ar: (cn,enH1) => `أفضل IPTV في ${cn} — بث مباشر ورياضة 4K`,
  },
  device: {
    fr: (slug,enH1) => enH1.includes('Android')?'IPTV sur Android — Regardez 20 000+ Chaînes 4K':enH1.includes('Firestick')?'Comment Installer IPTV sur Firestick — Guide Complet 2026':enH1.includes('iPhone')||enH1.includes('iOS')?'IPTV sur iPhone & iPad — Meilleures Apps iOS 2026':enH1.includes('Smart TV')?'Configurer IPTV sur Smart TV — Guide Samsung, LG, Sony 2026':enH1.includes('Samsung')?'IPTV sur Samsung — Guide Complet 2026':'IPTV sur '+slug+' — Guide Complet 2026',
    es: (slug,enH1) => enH1.includes('Android')?'IPTV en Android — Mira 20 000+ Canales 4K':enH1.includes('Firestick')?'Cómo Instalar IPTV en Firestick — Guía Completa 2026':enH1.includes('iPhone')||enH1.includes('iOS')?'IPTV en iPhone y iPad — Mejores Apps iOS 2026':enH1.includes('Smart TV')?'Configurar IPTV en Smart TV — Guía Samsung, LG, Sony 2026':enH1.includes('Samsung')?'IPTV en Samsung — Guía Completa 2026':'IPTV en '+slug+' — Guía Completa 2026',
    de: (slug,enH1) => enH1.includes('Android')?'IPTV auf Android — 20.000+ Sender in 4K':enH1.includes('Firestick')?'IPTV auf Firestick einrichten — Komplette Anleitung 2026':enH1.includes('iPhone')||enH1.includes('iOS')?'IPTV auf iPhone & iPad — Beste iOS Apps 2026':enH1.includes('Smart TV')?'IPTV auf Smart TV einrichten — Samsung, LG, Sony 2026':enH1.includes('Samsung')?'IPTV auf Samsung — Komplette Anleitung 2026':'IPTV auf '+slug+' — Komplette Anleitung 2026',
    it: (slug,enH1) => enH1.includes('Android')?'IPTV su Android — 20.000+ Canali 4K':enH1.includes('Firestick')?'Come Installare IPTV su Firestick — Guida Completa 2026':enH1.includes('iPhone')||enH1.includes('iOS')?'IPTV su iPhone e iPad — Migliori App iOS 2026':enH1.includes('Smart TV')?'Configurare IPTV su Smart TV — Samsung, LG, Sony 2026':enH1.includes('Samsung')?'IPTV su Samsung — Guida Completa 2026':'IPTV su '+slug+' — Guida Completa 2026',
    pt: (slug,enH1) => enH1.includes('Android')?'IPTV no Android — 20.000+ Canais 4K':enH1.includes('Firestick')?'Como Instalar IPTV no Firestick — Guia Completo 2026':enH1.includes('iPhone')||enH1.includes('iOS')?'IPTV no iPhone e iPad — Melhores Apps iOS 2026':enH1.includes('Smart TV')?'Configurar IPTV na Smart TV — Samsung, L
